### ISSUE TITLE
[Bug] Cant login to Greenlight on Fedora

### ISSUE THREAD

**Issue by Martinuuu** [unknownskl/xbox-xcloud-client#1168]
### Describe the bug

~~I recently switched from Arch Linux where Greenlight was working perfectly, to Fedora where there is a problem logging in to Greenlight.~~

After entering my credentials at the Microsoft website a window opens prompting me to open an obscure link with software on my computer: x-scheme-handler/ms-xal-000000004c20a908
![Screenshot from 2024-03-06 22-55-22](https://github.com/unknownskl/greenlight/assets/93876339/7125dcaa-4904-4923-820e-5f6c5c6c4203)

Closing this Window will result in an endless loading screen
![Screenshot from 2024-03-06 22-55-52](https://github.com/unknownskl/greenlight/assets/93876339/c05cbf3a-fe0b-48fd-a737-89a74d50a0c9)

### To Reproduce

1. Open Greenlight
2. Click Login
3. Login with Microsoft
4. Gnome "open with..." pops up
5. Close this window
6. Endless loading screen

### Environment

```markdown
- OS: Fedora Linux 39 Workstation
- DE: GNOME 45.4
- Kernel: 6.7.7-200.fc39.x86_64 
- Device: VivoBook_ASUSLaptop X515JAB_F515 
- Greenlight version: 2.2.0 Flatpak and Appimage
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by Martinuuu** [comment]
UPDATE:
Issue seems to only occur in version 2.2.0, Login possible in version 2.1.0 so Fedora is not the problem.

**Comment by Frdnspnzr** [comment]
I have the same problem on a Steam Deck. Console says getMediaAccessStatus is not a function so it looks like it was introduced with commit 69d2ff7.

**Comment by fedecocruz** [comment]
Same problem here on steam deck

**Comment by lzlaG** [comment]
Same with opensuse tumbleweed. I tried appimage and flatpak

**Comment by ReenigneArcher** [comment]
Same problem on Windows 11

**Comment by GazzaR66** [comment]
Same issue on steam deck, reverted to previous app image and it's ok.

**Comment by unknownskl** [comment]
Thanks and sorry for the delay. Issue has been identified and i will try to push out a new update asap.

**Comment by unknownskl** [comment]
v2.2.1 has been released which should fix the login issue. Please let me know if this fixes the issue on your side

**Comment by ReenigneArcher** [comment]
v2.2.1 is working on Windows 11, thank you!

**Comment by Martinuuu** [comment]
v2.2.1 fixed the issue for me! Login works perfectly.

**Comment by GazzaR66** [comment]
v2.2.1 fixed the issue for me, Login works on steam deck, thankyou.

**Comment by RogueCJR** [comment]
Currently experiencing an issue connecting to my console, everything up to date in terms of updates, was fine yesterday however now when trying to stream my xbox through greenlight i get the following error
failed to start new stream. error details: {"url":v5/sessions/home/play","status":401,"body":""}

**Comment by ReenigneArcher** [comment]
@RogueCJR I think your issue is different than the one originally posted here. This bug was that people actually couldn't login to Microsoft.

But, I randomly get the same issue you are mentioning. Is your console in standby mode? Does manually powering it on help?

**Comment by RogueCJR** [comment]
Ah my apologies.. No unfortunately not, it’s on powered on mode have tried
both standby and powered on and to no avail
Just keeps saying session not found afterwards
